---

- hosts: all
  vars_files:
    - vars.yml

  tasks:
    ##############################
    # Setup dependencies for kitty
    ##############################
    - name: Install required apt packages
      become: true
      apt:
        name: "{{item}}"
        state: "present"
        cache_valid_time: 600
      with_items:
        - "build-essential"
        - "cmake"
        - "fontconfig"
        - "git"
        - "libgl-dev"
        - "libosmesa-dev"
        - "libxi-dev"
        - "libxmu-dev"
        - "pkg-config"
        - "python3"
        - "python3-dev"
        - "software-properties-common"
        - "xorg-dev"
        - "xsel"

    - name: Setup kitty and dependency source directory
      file:
        path: "{{repo_base_dir}}"
        state: "directory"

    - name: Clone GLFW repo dependency for Kitty
      git:
        repo: "https://github.com/glfw/glfw.git"
        dest: "{{repo_base_dir}}/glfw"
        version: latest
        accept_hostkey: yes
        force: yes
        clone: yes
        update: yes

    - name: Build & install GLFW
      command: "{{item[0]}}"
      args:
        chdir: "{{repo_base_dir}}/glfw"
        creates: "{{item[1]}}"
      with_items:
        - [["cmake -DBUILD_SHARED_LIBS=ON .", "{{repo_base_dir}}/glfw/cmake_install.cmake"]]
        - [["make install", "/usr/local/lib/libglfw.so.3.2"]]
      become: true

    - name: Clone Glew repo dependency for Kitty
      git:
        repo: "https://github.com/nigels-com/glew.git"
        dest: "{{repo_base_dir}}/glew"
        version: glew-2.1.0
        accept_hostkey: yes
        force: yes
        clone: yes
        update: yes

    - name: Compile Glew
      command: "{{item[0]}}"
      args:
        chdir: "{{item[1]}}"
      with_items:
        - [["make", "{{repo_base_dir}}/glew/auto"]]
        - [["make glew.lib", "{{repo_base_dir}}/glew"]]

    - name: Install Glew
      command: "make install"
      args:
        chdir: "{{repo_base_dir}}/glew"
      become: true

    - name: Add libGLEW to LD Config
      copy:
        content: "/usr/lib64\n"
        dest: "/etc/ld.so.conf.d/libGLEW.conf"
      become: true

    - name: Refresh LD Config
      command: "ldconfig"
      become: true

    ##############################
    # Setup Kitty itself
    ##############################
    - name: Clone Kitty Repo
      git:
        repo: "https://github.com/kovidgoyal/kitty"
        dest: "{{repo_base_dir}}/kitty"
        accept_hostkey: yes
        clone: yes
        update: yes
        version: v0.3.0

    - name: Build Kitty
      command: "{{item}}"
      args:
        chdir: "{{repo_base_dir}}/kitty"
        creates: "{{repo_base_dir}}/kitty/linux-package"
      become: true
      with_items:
        - "python3 setup.py build"
        - "python3 setup.py linux-package"

    - name: Install Kitty
      file:
        src: "{{repo_base_dir}}/kitty/linux-package/{{item}}"
        dest: "/usr/{{item}}"
        state: link
      become: true
      with_items:
        - "bin/kitty"
        - "lib/kitty"
        - "share/applications/kitty.desktop"
        - "share/icons/hicolor/256x256/kitty.png"
        - "share/terminfo/x/xterm-kitty"

    - name: Setup kitty config directory
      file:
        path: "{{config_base_dir}}/kitty"
        state: "directory"

    - name: Symlink Kitty config
      file:
        src: "{{dotfiles_base_dir}}/kitty/kitty.conf"
        dest: "{{config_base_dir}}/kitty/kitty.conf"
        state: link
