---
# Install the base python packages plus their development libraries

- name: Ensure we have python 2 & 3 available
  become: true
  pacman:
    name: "{{item}}"
    state: "present"
    cache_valid_time: 600
  with_items:
    - "build-essential"
    - "python-dev"
    - "python-pip"
    - "python-virtualenv"
    - "python3"
    - "python3-dev"
    - "python3-pip"
