---
# Add the various python packages, plus build-essential, which allows various
# packages to build c extensions.

- name: Ensure we have python 2 & 3 available
  become: true
  apt:
    name: "{{item}}"
    state: "present"
    cache_valid_time: 600
  with_items:
    - "build-essential"
    - "python-dev"
    - "python-pip"
    - "python-virtualenv"
    - "python3"
    - "python3-dev"
    - "python3-pip"
    - "python3-venv"
