---

# Play to configure the system to my preferences

- hosts: all
  vars_files:
    - vars.yml

  tasks:
      - name: Copy password feedback config to /etc
        copy:
          src: "{{dotfiles_base_dir}}/system/pwfeedback"
          dest: "/etc/sudoers.d/pwfeedback"
          owner: root
        become: yes

