---

# Play to install and configure Tmux
- name: "Install tmux build dependencies"
  include_tasks: "packages.apt.yml"
  when: ansible_os_family == "Debian"

- name: "Symlink Tmux Config into place"
  file:
    src: "{{dotfiles_base_dir}}/tmux/tmux.conf"
    dest: "/home/{{user}}/.tmux.conf"
    state: link
    force: "yes"
  become: true
  become_user: "{{user}}"

- name: "Install latest Tmux from package repos"
  package:
    name: "tmux"
    state: present
  become: true
  when: ansible_os_family == "Archlinux"

- name: "Pull Tmux Release"
  get_url:
    url: "https://github.com/tmux/tmux/releases/download/{{tmux_version}}/tmux-{{tmux_version}}.tar.gz"
    dest: "/home/{{user}}/Downloads/tmux-{{tmux_version}}.tar.gz"
  tags:
    - install
  become: true
  become_user: "{{user}}"
  when: ansible_os_family == "Debian"

  # For some reason, unarchive can't locate the file downloaded above.
  # Fuck you, unarchive.
- name: Unpack Tmux
  command: "{{item}}"
  tags:
    - install
  become: true
  beome_user: "{{user}}"
  with_items:
    - "tar -xf /home/{{user}}/Downloads/tmux-{{tmux_version}}.tar.gz -C {{personal_code_base_dir}}"
    - "chown -R {{user}}:{{user}} {{personal_code_base_dir}}"
  when: ansible_os_family == "Debian"

- name: "Build Tmux"
  command: "{{item}}"
  args:
    chdir: "{{personal_code_base_dir}}/tmux-{{tmux_version}}/"
  with_items:
    - "./configure"
    - "make"
  become: true
  become_user: "{{user}}"
  when: ansible_os_family == "Debian"
  tags:
    - skip_ansible_lint

- name: "Install Tmux"
  command: make install
  args:
    chdir: "{{personal_code_base_dir}}/tmux-{{tmux_version}}/"
  become: true
  when: ansible_os_family == "Debian"
  tags:
    - skip_ansible_lint

- name: "Pull in Tmux Plugin Manager"
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "/home/{{user}}/.tmux/plugins/tpm"
    version: master
    accept_hostkey: "yes"
    clone: "yes"
    update: "yes"
  become: true
  become_user: "{{user}}"

- name: "Install & Update Tmux Plugins"
  shell: "source /home/{{user}}/.bashrc && {{item}}"
  args:
    executable: /bin/bash
  with_items:
    - "/home/{{user}}/.tmux/plugins/tpm/bin/install_plugins"
    - "/home/{{user}}/.tmux/plugins/tpm/bin/update_plugins all"
  # when: tpm_installed.changed
  become: true
  become_user: "{{user}}"
  environment:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
  tags:
    - skip_ansible_lint
