---

- name: Install required apt packages
  become: true
  apt:
    name: "{{item}}"
    state: "present"
    cache_valid_time: 600
  with_items:
    - "build-essential"
    - "cmake"
    - "git"
    - "libevent-dev"
    - "libncurses5-dev"
    - "ncurses-base"
    - "pkg-config"
