---

# Play to configure the various tools I use on a regular basis

- hosts: all
  vars_files:
    - vars.yml

  tasks:
      - name: Ensure we have python 2 & 3 available
        become: true
        apt:
          name: "{{item}}"
          state: "present"
          cache_valid_time: 600
        with_items:
          - "python-dev"
          - "python-pip"
          - "python-virtualenv"
          - "python3"
          - "python3-dev"
          - "python3-pip"

      - name: Pull in Pipsi
        get_url:
          url: "https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py"
          dest: "/tmp/get-pipsi.py"
        become: yes

      - name: Install pipsi
        command: "python3 /tmp/get-pipsi.py"

      - name: Install pipenv, glances
        command: pipsi install {{item[0]}}
        args:
          creates: "{{python_bin_dir}}/{{item[1]}}"
        with_items:
          - [["glances", "glances"]]
          - [["pipenv", "pipenv"]]
          - [["powerline-status", "powerline"]]

