---

# Play to install and configure Tmux

- hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Install required apt packages
      become: true
      apt:
        name: "{{item}}"
        state: "present"
        cache_valid_time: 600
      with_items:
        - "build-essential"
        - "cmake"
        - "git"
        - "libevent-2.0-5"
        - "libevent-dev"
        - "libncurses5-dev"
        - "ncurses-base"
        - "pkg-config"
      when: ansible_os_family == "Debian"
      tags:
        - install

    - name: Symlink Tmux Config into place
      file:
        src: "{{dotfiles_base_dir}}/tmux/tmux.conf"
        dest: "/home/{{user}}/.tmux.conf"
        state: link
        force: yes
      tags:
        - config

    - name: Pull Tmux Release
      get_url:
        url: https://github.com/tmux/tmux/releases/download/2.6/tmux-2.6.tar.gz
        dest: "/home/{{user}}/Downloads/"
      when: ansible_os_family == "Debian"
      tags:
        - install

    - name: Unpack Tmux
      unarchive:
        src: "/home/{{user}}/Downloads/tmux-2.6.tar.gz"
        dest: "{{personal_code_base_dir}}/"
      when: ansible_os_family == "Debian"
      tags:
        - install

    - name: Build Tmux
      command: "{{item}}"
      args:
        chdir: "{{personal_code_base_dir}}/tmux-2.6/"
      with_items:
        - "./configure"
        - "make"
      when: ansible_os_family == "Debian"
      tags:
        - install

    - name: Install Tmux
      command: make install
      args:
        chdir: "{{personal_code_base_dir}}/tmux-2.6/"
      become: true
      when: ansible_os_family == "Debian"
      tags:
        - install

    - name: Pull in Tmux Plugin Manager
      git:
        repo: "https://github.com/tmux-plugins/tpm"
        dest: "/home/{{user}}/.tmux/plugins/tpm"
        version: master
        accept_hostkey: yes
        force: yes
        clone: yes
        update: yes
      tags:
        - config

    - name: Install & Update Tmux Plugins
      command: "{{item}}"
      with_items:
        - "/home/sam/.tmux/plugins/tpm/bin/install_plugins"
        - "/home/sam/.tmux/plugins/tpm/bin/update_plugins all"
      environment:
        TMUX_PLUGIN_MANAGER_PATH: "/home/sam/.tmux/plugins/"
      tags:
        - config

    - name: "Symlink Powerline theme into place."
      file:
        src: "{{dotfiles_base_dir}}/powerline"
        dest: "{{config_base_dir}}/powerline"
        state: link
        force: yes
      tags:
        - config

