---

# Play to configure ZSH

- hosts: all
  vars_files:
    - vars.yml

  tasks:
      - name: Install ZSH
        become: true
        apt:
          name: "{{item}}"
          state: "present"
          cache_valid_time: 600
        with_items:
          - "zsh"

      - name: Symlink ZSH configs
        file:
          src: "{{dotfiles_base_dir}}/zsh/zshrc"
          dest: "/home/{{user}}/.zshrc"
          state: link

      - name: Ensure user's .config exists
        file:
          path: "/home/{{user}}/.config"
          state: directory

      - name: Ensure users zsh completion directory exists
        file:
          path: "/home/{{user}}/.zsh/completion"
          state: directory

      - name: pull zplug installer
        git:
          repo: "https://github.com/zplug/zplug"
          dest: "/home/{{user}}/.config/zplug"
          clone: yes
          update: yes

      - name: pull docker completion file for ZSH
        get_url:
          url: "https://github.com/docker/cli/raw/master/contrib/completion/zsh/_docker"
          dest: "/home/{{user}}/.zsh/completion/_docker"

