---

# Play to configure the various tools I use on a regular basis

- hosts: all
  vars_files:
    - vars.yml

  tasks:
      - name: Copy password feedback config to /etc
        copy:
          src: "{{dotfiles_base_dir}}/system/pwfeedback"
          dest: "/etc/sudoers.d/pwfeedback"
          owner: root
        become: yes

      - name: Setup mosh
        apt:
          name: mosh
          cache_valid_time: 600
        become: yes

