---
- name: add neovim repo
  become: true
  apt_repository:
    repo: "ppa:neovim-ppa/stable"

- name: install apt requirements
  become: true
  apt:
    name: "{{item}}"
    state: "present"
    cache_valid_time: 600
  with_items:
    - "exuberant-ctags"
    - "git"
    - "neovim"
    - "python-dev"
    - "python-pip"
    - "python-virtualenv"
    - "python3"
    - "python3-dev"
    - "python3-pip"
    - "ruby"
    - "ruby-dev"
    - "software-properties-common"
