---
- name: install role requirements
  become: true
  pacman:
    name: "{{item}}"
    state: "present"
  with_items:
    - "exuberant-ctags"
    - "git"
    - "neovim"
    - "python-dev"
    - "python-pip"
    - "python-virtualenv"
    - "python3"
    - "python3-dev"
    - "python3-pip"
    - "ruby"
    - "ruby-dev"
    - "software-properties-common"
